### PR TITLE
t.declare([name]) enables construction of recursive types

### PR DESCRIPTION
**Pull request by utaal**
This code contains a proposed pseudo-combinator to enable the construction of recursive types (https://github.com/gcanti/tcomb/issues/71). The proposed API is described in the "Recusive types" section of the GUIDE.

This is a minimal addition that (to my knowledge) doesn't break existing features and does not require changes to the existing combinators. The `displayName` path for unnamed structs sometimes contains the type name (or a placeholder, when an explicit name was not provided) for types constructed via `declare`, e.g.
`{value: Int, b: B}/b: B` where `B` is in fact `{a: A}`. This is mainly due to limitations of the proposed implementation, but - in general - it would anyway not be possible to represent all the (mutually recursive) struct types with their fields (it would not terminate).

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @utaal, thanks a lot! A very clever idea. 

Some tweaks to your proposal (not sure they are 100% correct though)

```js
function declare(name) {
  if (process.env.NODE_ENV !== 'production') {
    assert(isTypeName(name), function () { return 'Invalid argument name ' + name + ' supplied to declare([name]) (expected a string)'; });
  }

  var type; // refcell is required?

  function Declare(value, path) {
    if (process.env.NODE_ENV !== 'production') {
      // using isNil for consistency
      assert(!isNil(type), function () { return 'Type declared but not defined, don\'t forget to call .define on every declared type'; });
    }
    return type(value, path);
  }

  Declare.define = function (spec) {
    if (process.env.NODE_ENV !== 'production') {
      // added "argument" to error message for consitency
      assert(isType(spec), function () { return 'Invalid argument type ' + exports.stringify(spec) +  ' supplied to define(type) (expected a type)'; });
      // using isNil for consistency
      assert(isNil(type), function () { return 'Declare.define(type) can only be invoked once'; });
    }

    type = spec;
    // using mixin for consistency
    mixin(Declare, type, true); // true because it overwrites Declare.displayName
    if (name) { // else keep spec infos
      Declare.displayName = Declare.meta.name = name; // support for Tree.displayName === Tree.meta.name === 'Tree'
    }
    Declare.prototype = type.prototype; // support for (bst instanceof Tree) === true
  };

  Declare.displayName = name;
  return Declare;
}
```

And then

```js
var Tree = declare('Tree');

Tree.define(t.struct({
  value: t.Number,
  left: t.maybe(Tree),
  right: t.maybe(Tree)
}));

// deserialization form JSON
var bst = new Tree({
  value: 5,
  left: {
    value: 2
  },
  right: {
    left: {
      value: 6
    },
    value: 7
  }
});

// all true...
console.log(Tree.is(bst));
console.log(bst instanceof Tree);
console.log(Tree.displayName === 'Tree');
console.log(Tree.meta.name === 'Tree');
console.log(Tree.meta.props.left.meta.type === Tree);
```

What do you think?

**Comment by gcanti** [comment]
"unsafe" version supporting method definition (before and after `define`)

```js
function declare(name) {
  if (process.env.NODE_ENV !== 'production') {
    assert(isTypeName(name), function () { return 'Invalid argument name ' + name + ' supplied to declare([name]) (expected a string)'; });
  }

  var type;

  function Declare(value, path) {
    if (process.env.NODE_ENV !== 'production') {
      assert(!isNil(type), function () { return 'Type declared but not defined, don\'t forget to call .define on every declared type'; });
    }
    return type(value, path);
  }

  Declare.define = function (spec) {
    if (process.env.NODE_ENV !== 'production') {
      assert(isType(spec), function () { return 'Invalid argument type ' + exports.stringify(spec) +  ' supplied to define(type) (expected a type)'; });
      assert(isNil(type), function () { return 'Declare.define(type) can only be invoked once'; });
    }

    type = spec;
    // this is unsafe if spec is not "fresh"
    mixin(spec.prototype, Declare.prototype);
    mixin(Declare, type, true /* overwrites displayName*/);
    Declare.displayName = name || spec.displayName;
    Declare.meta.name = name;
    Declare.prototype = type.prototype;
  };

  Declare.displayName = name;
  return Declare;
}
```

And then

```js
var Tree = declare('Tree');

function before() {}
function after() {}

Tree.prototype.before = before; // before definition

Tree.define(t.struct({
  value: t.Number,
  left: t.maybe(Tree),
  right: t.maybe(Tree)
}));

Tree.prototype.after = after; // after definition

// deserialization form JSON
var bst = new Tree({
  value: 5,
  left: {
    value: 2
  },
  right: {
    left: {
      value: 6
    },
    value: 7
  }
});

// all true
console.log(Tree.is(bst));
console.log(bst instanceof Tree);
console.log(Tree.displayName === 'Tree');
console.log(Tree.meta.name === 'Tree');
console.log(bst.before === before)
console.log(bst.after === after)
```

**Tuple example**

```js
var List = declare('List');

List.define(t.tuple([t.Number, t.maybe(List)]));

var list = List([1, [2, null]]);

console.log(List.is(list));
console.log(list instanceof Array);
console.log(List.displayName === 'List');
console.log(List.meta.name === 'List');
```

**Comment by mlegenhausen** [comment]
+1

**Comment by utaal** [comment]
I have the feeling that it may be useful to determine whether, in
```js
var A = t.declare('A');
var B = t.struct({ ... });
A.define(B);
```
`A` and `B` should be considered the same (A is an alias of B) or two separate types. This could drive some of the choices that are implicit in your code. They may _need_ to be considered two disparate types because adding "static" function to A won't magically add them to B and viceversa - but this could also be considered a small culprit of this implementation.

Also, is the fact that `AStruct({ ... }) instanceof AStruct` part of the public API? It only seems to be true for structs (not for `t.Num`, for example) and aliasing the prototype may be dangerous (especially if we consider `A` and `B` in the previous example to be two different types.

**Comment by utaal** [comment]
I'm currently leaning torwards having a `define`-d type be an alias and require that the provided type is fresh - I'll push a couple of commits in that direction. That code contains some of the contracts you expressed as `console.log`s in tests so it may be a good starting point to experiment with different implementations / different contracts.

**Comment by gcanti** [comment]
I like it, I'm going to merge. 

Minor nitpick:

```js
// increment only when strictly necessary
Declare.displayName = name || ( getTypeName(Declare) + '$' + nextDeclareUniqueId++ );
// nextDeclareUniqueId += 1;
```

**Comment by gcanti** [comment]
Also, what about a `recursive` boolean added to the `meta` object?

```js
Declare.meta.recursive = true;
```

Libraries performing type introspection (i.e. tools for generating documentation from tcomb types or tcomb-form) would be grateful instead of just explode :)

**Comment by utaal** [comment]
`recursive` would be a warning to be careful recursing into referenced types, right? A `declare`-d type is probably but not necessarily recursive. What about `maybeRecursive` (or something similar)?

I'll also add to the Guide the requirement that the type provided to `.define` has to be fresh.

**Comment by gcanti** [comment]
Yes, at least a warning. Maybe more than a warning though: not sure but, excluding naive development errors, are there legit use cases for using `declare` other than defining a recursive (or mutually recursive) type?

**Comment by utaal** [comment]
The only other case I can think off the top of my head is defining types that form a DAG of dependencies: currently you must define them in topological order (because they need to have all their dependencies available at definition type).
E.g. this doesn't work (obviously):
```js
var t = require('tcomb');

var B = t.struct({
  a: A
});

var A = t.struct({
  value: t.Num
});
```

`t.declare` would allow you to do something like:
```js
var A = t.declare('A');
var B = t.declare('B');

B.define(t.struct({
  a: A
}));

A.define(t.struct({
  value: t.Num
}));
```
where the definitions can be in any order, sidestepping the need to determine a topological ordering. This is especially useful for generating complex tcomb type collections via automated tools (such as https://github.com/buildo/metarpheus).

**Comment by giogonzo** [comment]
wohooo :beers: 

very nice

> What about maybeRecursive (or something similar)?


to be even nicer with introspection tools, we could have both `declared` and `defined` (or `recursive`) as boolean meta props, set only after `declare` time and `define` time

**Comment by gcanti** [comment]
@utaal I see. So `declare/define` would be an effective and alternative way to define tcomb types. From this POV I guess an additional boolean doesn't really matter

**Pull request merged**
