### PR TITLE
Circular references in struct

### PR DESCRIPTION
**Pull request by rubengrill**
With the new `t.declare` it is now possible to have a reference from a struct to itself, either directly or indirectly (struct has reference to another type that has a reference to the struct again).

When an object is passed to the struct constructor with cyclic references, this leads to an infinite loop right now.

This PR adds a new state that is passed beside `path` when creating a type instance: `identityMap`.
This identityMap contains a mapping of value to the created struct instance.
Whenever the same value (identity) is requested again, the already created one is returned instead.
Because of the indirect references, this state has to be passed for every type.
Note that no plain javascript object can be used as IdentityMap, as keys are coerced to strings.
That's why this PR also contains a simple implementation of IdentityMap.

Because I wanted to debug code, I also added karma, so I was able to debug the code in Chrome.
By default it runs in PhantomJS, so it should not be a big difference.
A big benefit is the file watcher though, re-executing all tests whenever a file has changed.

As I'm developing in vim, I also added .editorconfig, this might also be helpful for others.

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @rubengrill, thanks for this PR, very interesting.

While I can see the value of defining recursive types, I'm not (yet) sold on supporting recursive values. 

Anyway, after playing some hours with your code I have a couple of observations:

- maybe `IdentityMap`'s interface should comply with `Map` (`set` method instead of `put`)
- then the algorithm could use native `Map` if available (arguably better performances?)
- if `Map` (or `WeakMap`?) is not available fallback to a simple surrogate (`IdentityMap`)
- I guess `tuple`s should be protected as well

```js
//
// tuples
//

const List = t.declare('List');

List.define(t.tuple([t.Number, t.maybe(List)]));

const list = [42];
list[1] = list;

console.log(List(list)); // infinite loop
```

Due to how the algorithm works, there are monsters lurking in the shadow... however they are corner cases and probably doesn't matter:

```js
//
// monsters
//

const A = t.declare('A');
const B = t.declare('B');

A.define(t.struct({
  value: t.Number,
  b: B
}));

B.define(t.struct({
  value: t.Number,
  b: A
}));

const monster = {value: 1};
monster.b = monster;

console.log(A(monster).b): // <= should be an instance of B, but it's an instance of A
```

/cc @utaal

**Comment by utaal** [comment]
There seem two be two separate (but related) issues in play here. One is the ability to typecheck (and construct tcomb wrappers for) values with cyclical references. The other, which is not directly related to the existence of `declare`, is support for DAGs in addition to trees, for example:
```js
    var A = t.struct({
      value: t.Num
    });

    var B = t.struct({
      a1: A,
      a2: A
    });

    var a = { value: 3 };
    var b = B({
      a1: a,
      a2: a
    });
    assert.ok(b.a1 === b.a2);
```
This fails, as two separate instances of A are created.

I've attempted implementing support for both, similarly to @rubengrill, and ended up with this https://github.com/utaal/tcomb/pull/1 which is very similar in spirit but has the advantage of not failing in the "monster" case pointed out by @gcanti. Important to note that this (and @rubengrill's) only supports recursive values where the outmost type is a struct: if that's not the case (as in @gcanti's example) the typechecking doesn't terminate for cyclical references and non-tree-like references (as in my previous example) do not preserve instance equality.

My current feeling is that supporting cyclical and non-tree-like references cleanly may require an API where every type construction goes through a single point where it can be intercepted (`create` might already be enough, but I'm not entirely sure).

Hope this helps.

**Comment by gcanti** [comment]
@utaal @rubengrill I just pushed to master a synthesys of your work

> may require an API where every type construction goes through a single point where it can be intercepted

`declare/define` seems the natural candidate, so that only users of `declare` will pay the (probably negligible) additional price of `identityMap` and `recursionDepth`

All tests are green: TreeItem, monster and also my tuples example.

Let me know if it's a good basis for further work.

Implementation: https://github.com/gcanti/tcomb/blob/master/index.js#L1025

**Comment by utaal** [comment]
>> may require an API where every type construction goes through a single point where it can be intercepted

> declare/define seems the natural candidate, so that only users of declare will pay the (probably negligible) additional price of identityMap and recursionDepth

While yours seems to be a reasonable approach to support cyclical and non-tree references for recursive types, I was refererring to the more general issue (which may or may not be interesting per se) of how to support non-tree references for all types:

```js
    var A = t.struct({
      value: t.Num
    });

    var B = t.struct({
      a1: A,
      a2: A
    });

    var a = { value: 3 };
    var b = B({
      a1: a,
      a2: a
    });
    assert.ok(b.a1 === b.a2);
```
This still fails and it's unclear why this should not be supported while [this](https://github.com/gcanti/tcomb/commit/b69096d632bb62d4175ad491396faa5dedc3f862#diff-e3b713220c4c0d1ec8321e320bf5409bR170) is.

Also to note, the following test also fails with both my implementation and @gcanti's but succeeds with @rubengrill's.
```js
      var A = t.declare('A');

      var B = t.struct({
        a1: A,
        a2: A
      });

      A.define(t.struct({
        value: t.Num
      }));

      var a = { value: 3 };
      var b = B({
        a1: a,
        a2: a
      });
      assert.ok(b.a1 === b.a2);
    });
```

**Comment by rubengrill** [comment]
@gcanti Is the last commit #7ab8196 valid?

Current status:

I added tests that should cover all edge cases we discussed here so far (please correct me if some are missing).
I also merged the tests of your branch gcanti/cyclic @gcanti, so that we can speak about the same tests.

What doesn't work in this PR:
- Tuple.is() does not check for cyclic references
- Indirect cyclic references (in the test there is a t.dict between) lead to different instances of tuples
- @gcanti Monster example

I just replaced the index.js with the index.js of gcanti/cyclic and following tests failed there:
cyclic references should allow cyclic references in tuples (Line 186)
cyclic references should allow indirect cyclic references in tuples (Line 206)
cyclic references should return same instances when the same instance is used multiple times in a struct (Line 252)
cyclic references should return same instances when the same instance is used multiple times in a tuple (Line 265)

**Comment by rubengrill** [comment]
Fixing test "cyclic references should allow indirect cyclic references in tuples" seems to be really hard with the current solution.

When a tuple is created and the value is contained in identityMap, then it is not (yet) clear if the mapped value is the correct one, depending if idempotent or not:

It could be either (https://github.com/rubengrill/tcomb/blob/master/index.js#L693) or (https://github.com/rubengrill/tcomb/blob/master/index.js#L704), depending if other values within the tuple changed or not (https://github.com/rubengrill/tcomb/blob/master/index.js#L699)

**Comment by gcanti** [comment]
> Is the last commit 7ab8196 valid?

@rubengrill Yes, it is

**Comment by rubengrill** [comment]
Circular references works now also for tuples.
The implementation is as follows:

- Instead of identityMap there is now a treeState passed
- treeState contains all cycle entries (value that is accessed at least twice)
- treeState contains state per value, where type of value defines the content of state
- required is only the attribute `idempotent`
- For a tuple the state of the for loop is also contained in the state
  When a cycle is detected, the for loop is continued with the next element
  When the first for loop for a value get's control again, it skips all remaining items, as state.i has moved
- The decision for idempotence is only done when the first loop of a value get's control again.
  Until then, all tuple calls are treating the value as not idempotent, which means they return a newly constructed array.
  As this means that actual is always !== instance, treeState has a helper method isIdempotent that returns idempotent attribute of the value's state if any.

- Monsters are now also handled, structs use another map for this, mapping type <> instance

**Comment by rubengrill** [comment]
Any news here @gcanti ?

**Comment by gcanti** [comment]
Hi @rubengrill,
there's a lot of code here, I must find the time to review this PR. Alas, I have a bit too much on my hands these days.

My plan for the short term:

1. wait for a last PR by @utaal (docs on `declare`)
2. release v2.6 with the new feature
3. carefully review your code

Circular references are tricky, my gut feeling is that it might not be worth it. 
In particular I'm concerned about circular structures and immutability.

**Comment by rubengrill** [comment]
Ok, thanks for the update

**Comment by gcanti** [comment]
Closing for inactivity. Thanks again @rubengrill for this PR.

**Pull request closed without merging**
