### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by beac0n**
highlight differences in production mode

### CODE REVIEW

**Comment by gcanti** [comment]
Thanks

**Comment by worc** [comment]
i think we're missing what the differences are and why there are differences.

**Comment by beac0n** [comment]
afaik it is just inefficient @gcanti ?

**Comment by sheldon-b** [comment]
I agree with @worc -- I wish this had any detail about why tcomb shouldn't be used in production even if it were as minor as, "tcomb is not recommended for production because we prioritize it as a development tool over efficiency and so it may be slow for production applications".

**Pull request merged**
